config/routes.rb
Rails.application.routes.draw do
  root 'short_urls#new'
  resources :short_urls, only: %i[new create show]

  get :follow, to: 'short_urls#follow', as: 'follow_short_url'

  namespace :api, constraints: lambda { |req| [:json].include?(req.format.to_sym) } do
    namespace :v1 do
      resources :short_urls, only: :index
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/short_url.rb
class ShortUrl < ApplicationRecord
  has_many :user_infos
  has_secure_token

  validates :long, presence: true

  before_save :check_url

  private

  def check_url
    self.long = "http://#{long}" unless /^(http|https)/ =~ long
  end
end

app/models/user_info.rb
class UserInfo < ApplicationRecord
  belongs_to :short_url
end

app/controllers/api/api_controller.rb
class Api::ApiController < ActionController::Base
  protect_from_forgery with: :null_session
end

app/controllers/api/v1/short_urls_controller.rb
class Api::V1::ShortUrlsController < Api::ApiController
  def index
    render json: ShortUrl.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/short_urls_controller.rb
class ShortUrlsController < ApplicationController
  before_action :set_short_url, only: :show
  before_action :set_short_url_by_token, only: :follow

  # GET /short_urls/1
  def show; end

  # GET /short_urls/new
  def new
    @short_url = ShortUrl.new
  end

  # POST /short_urls
  def create
    @short_url = ShortUrl.find_or_initialize_by(short_url_params)

    respond_to do |format|
      if @short_url.save
        format.html { redirect_to @short_url, notice: 'Short url was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def follow
    UserInfoFactory.create(@short_url, request)
    redirect_to @short_url.long
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_short_url
    @short_url = ShortUrl.find(params[:id])
  end

  def set_short_url_by_token
    @short_url = ShortUrl.find_by_token(params[:token])
  end
  # Never trust parameters from the scary internet, only allow the white list through.
  def short_url_params
    params.require(:short_url).permit(:long)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shorturl</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <div class="header">
      <%= link_to 'Short URL', root_path, class: 'logo' %>
      <div class="header-right">
        <%= link_to 'Home', root_path, class: 'active' %>
        <!--<a href="#contact">Login</a>-->
        <!--<a href="#about">About</a>-->
      </div>
    </div>

    <div style="padding-left:20px">
      <%= yield %>
    </div>

  </body>
</html>

app/views/short_urls/_form.html.erb
<%= form_with(model: short_url, local: true) do |form| %>
  <% if short_url.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(short_url.errors.count, "error") %> prohibited this short_url from being saved:</h2>

      <ul>
      <% short_url.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :long, 'Long url' %>
    <%= form.text_area :long %>
  </div>

  <div class="actions">
    <%= form.submit 'Shorten url' %>
  </div>
<% end %>

app/views/short_urls/new.html.erb
<h1>Enter your url</h1>

<%= render 'form', short_url: @short_url %>

app/views/short_urls/show.html.erb
<h2>Click here to follow your link</h2>
<p>
  <%= link_to "<< Follow >> #{follow_short_url_url(token: @short_url.token)}",
              follow_short_url_path(token: @short_url.token) %>
</p>